import { useState } from 'react';
import { jsPDF } from 'jspdf';
import WealthMeter from './WealthMeter';
import FairnessExplainer from './FairnessExplainer';
import ComparisonChart from './ComparisonChart';
import TraditionalComparison from './TraditionalComparison';

const API_URL = import.meta.env.VITE_API_URL || '';

const rateColorMap = {
  'Very Low': 'bg-emerald-100 text-emerald-800',
  'Low': 'bg-lime-100 text-lime-800',
  'Moderate': 'bg-amber-100 text-amber-800',
  'Standard': 'bg-orange-100 text-orange-800',
  'High': 'bg-red-100 text-red-800',
};

const priorityColorMap = {
  'Urgent': 'bg-red-100 text-red-700 border-red-200',
  'Suggested': 'bg-amber-100 text-amber-700 border-amber-200',
  'Optional': 'bg-blue-100 text-blue-700 border-blue-200',
};

export default function LoanProfileCard({ profile, wealthContext, loanAmount, applicantData }) {
  const p = profile;
  const [explainOpen, setExplainOpen] = useState(false);
  const [schemes, setSchemes] = useState(null);
  const [schemesLoading, setSchemesLoading] = useState(false);
  const [schemesError, setSchemesError] = useState('');

  const downloadPDF = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = margin;
    const lineHeight = 7;

    const addLine = (text, fontSize = 11, isBold = false) => {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', isBold ? 'bold' : 'normal');
      const lines = doc.splitTextToSize(text, 170);
      lines.forEach(line => {
        doc.text(line, margin, y);
        y += lineHeight;
      });
    };

    const addGap = (h = 4) => { y += h; };

    // Header
    doc.setFillColor(5, 150, 105);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('FairLoan AI — Loan Profile Report', margin, 22);
    y = 45;
    doc.setTextColor(0, 0, 0);

    addLine(`Date: ${new Date().toLocaleDateString('en-IN')}`, 10);
    addGap(6);

    addLine('LOAN ASSESSMENT', 16, true);
    addGap();
    addLine(`Amount Requested: Rs. ${Number(loanAmount).toLocaleString('en-IN')}`);
    addLine(`Recommended Limit: Rs. ${Number(p.loan_limit_inr).toLocaleString('en-IN')}`);
    addLine(`Interest Rate: ${p.interest_rate_annual_percent}% (${p.interest_rate_label})`);
    addLine(`Repayment Schedule: ${p.repayment_schedule}`);
    addLine(`Collateral: ${p.collateral_requirement}`);
    addGap(6);

    addLine('COMMUNITY CONTEXT', 14, true);
    addGap();
    addLine(`Wealth Percentile: ${wealthContext.wealth_percentile}th (${wealthContext.relative_wealth_label})`);
    addLine(`Regional Median Income: Rs. ${Number(wealthContext.regional_median_income).toLocaleString('en-IN')}`);
    addLine(`Sample Size: ${wealthContext.sample_size} farmers`);
    addGap(6);

    addLine('FAIRNESS ASSESSMENT', 14, true);
    addGap();
    addLine(`Fairness Score: ${p.fairness_score}/10`);
    addLine(`${p.fairness_explanation}`);
    addGap(4);
    addLine(`Risk Rating: ${p.risk_rating}`);
    addGap(6);

    addLine('WHY THESE TERMS', 14, true);
    addGap();
    addLine(p.wealth_context_note);
    addGap(4);
    addLine(p.collateral_explanation);
    addGap(4);
    addLine(p.loan_limit_reasoning);
    addGap(6);

    if (p.recommendations?.length > 0) {
      addLine('RECOMMENDATIONS', 14, true);
      addGap();
      p.recommendations.forEach(r => {
        addLine(`[${r.priority}] ${r.title}`, 11, true);
        addLine(r.description);
        addGap(2);
      });
    }

    // Footer
    addGap(8);
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('Generated by FairLoan AI — Community-powered fair lending', margin, y);

    doc.save('FairLoan_Profile_Report.pdf');
  };

  // --- Scheme Matcher ---
  const fetchSchemes = async () => {
    if (!applicantData) return;
    setSchemesLoading(true);
    setSchemesError('');
    try {
      const res = await fetch(`${API_URL}/api/schemes`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(applicantData),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to fetch schemes');
      setSchemes(data.schemes);
    } catch (err) {
      setSchemesError(err.message);
    } finally {
      setSchemesLoading(false);
    }
  };

  // --- Explainability helpers ---
  const percentile = wealthContext.wealth_percentile;
  const region = applicantData?.region || 'your region';
  const rateDirection = p.interest_rate_annual_percent < 12 ? 'down' : 'up';

  return (
    <div className="space-y-6 animate-slide-up" id="loan-profile-results">
      {/* Header Card */}
      <div className="card p-6 sm:p-8 bg-gradient-to-br from-white to-brand-50/30">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
          <h2 className="text-2xl font-bold text-stone-900">Your Loan Profile</h2>
          <button onClick={downloadPDF} className="btn-secondary text-sm" id="btn-download-pdf">
            <svg className="w-4 h-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12M12 16.5V3" />
            </svg>
            Download PDF
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {/* Loan Amount */}
          <div className="p-4 bg-white rounded-xl border border-stone-200">
            <p className="text-xs text-stone-400 uppercase font-semibold mb-1">Requested</p>
            <p className="text-2xl font-bold text-stone-900">₹{Number(loanAmount).toLocaleString('en-IN')}</p>
          </div>
          {/* Recommended Limit */}
          <div className="p-4 bg-white rounded-xl border border-stone-200">
            <p className="text-xs text-stone-400 uppercase font-semibold mb-1">Recommended Limit</p>
            <p className="text-2xl font-bold text-brand-600">₹{Number(p.loan_limit_inr).toLocaleString('en-IN')}</p>
            <p className="text-xs text-stone-400 mt-1">{p.loan_limit_reasoning}</p>
          </div>
          {/* Interest Rate */}
          <div className="p-4 bg-white rounded-xl border border-stone-200">
            <p className="text-xs text-stone-400 uppercase font-semibold mb-1">Interest Rate</p>
            <div className="flex items-baseline gap-2">
              <p className="text-3xl font-extrabold text-stone-900">{p.interest_rate_annual_percent}%</p>
              <span className={`chip text-xs ${rateColorMap[p.interest_rate_label] || 'bg-stone-100 text-stone-600'}`}>
                {p.interest_rate_label}
              </span>
            </div>
          </div>
        </div>

        {/* Repayment + Collateral badges */}
        <div className="flex flex-wrap gap-3 mt-4">
          <div className="chip-blue">
            <svg className="w-3.5 h-3.5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
            </svg>
            {p.repayment_schedule}
          </div>
          <div className="chip-yellow">
            <svg className="w-3.5 h-3.5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z" />
            </svg>
            {p.collateral_requirement}
          </div>
        </div>
        <p className="text-sm text-stone-500 mt-2">{p.collateral_explanation}</p>
      </div>

      {/* Wealth Meter */}
      <WealthMeter
        percentile={wealthContext.wealth_percentile}
        label={wealthContext.relative_wealth_label}
        sampleSize={wealthContext.sample_size}
      />

      {/* Fairness Explainer */}
      <FairnessExplainer score={p.fairness_score} explanation={p.fairness_explanation} />

      {/* FEATURE 1 — Explainability Panel */}
      <div className="card overflow-hidden" id="explainability-panel">
        <button
          onClick={() => setExplainOpen(!explainOpen)}
          className="w-full flex items-center justify-between p-5 text-left hover:bg-stone-50 transition-colors duration-200"
          id="btn-toggle-explain"
        >
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-violet-100 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-violet-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z" />
              </svg>
            </div>
            <div>
              <h4 className="font-bold text-stone-900 text-sm">Why did you get this rate?</h4>
              <p className="text-xs text-stone-400">Step-by-step breakdown of how your rate was calculated</p>
            </div>
          </div>
          <svg
            className={`w-5 h-5 text-stone-400 transition-transform duration-300 ${explainOpen ? 'rotate-180' : ''}`}
            fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
          </svg>
        </button>

        {explainOpen && (
          <div className="px-5 pb-5 space-y-4 animate-fade-in border-t border-stone-100">
            {/* Step 1: Percentile */}
            <div className="flex items-start gap-3 pt-4">
              <div className="w-7 h-7 bg-violet-600 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-white text-xs font-bold">1</span>
              </div>
              <div>
                <p className="text-sm text-stone-700 font-medium">Community Ranking</p>
                <p className="text-sm text-stone-500 mt-0.5">
                  Your wealth percentile in <span className="font-semibold text-violet-700">{region}</span> is{' '}
                  <span className="font-bold text-violet-700">{percentile}th</span> — meaning{' '}
                  <span className="font-semibold">{100 - percentile}%</span> of farmers in your area have more assets.
                </p>
              </div>
            </div>

            {/* Step 2: Rate adjustment */}
            <div className="flex items-start gap-3">
              <div className="w-7 h-7 bg-violet-600 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-white text-xs font-bold">2</span>
              </div>
              <div>
                <p className="text-sm text-stone-700 font-medium">Rate Adjustment</p>
                <p className="text-sm text-stone-500 mt-0.5">
                  This moved your base rate from <span className="font-semibold">12%</span> {rateDirection} to{' '}
                  <span className="font-bold text-brand-700">{p.interest_rate_annual_percent}%</span>.
                </p>
              </div>
            </div>

            {/* Step 3: Wealth context card */}
            <div className="ml-10 p-4 bg-gradient-to-r from-violet-50 to-indigo-50 rounded-xl border border-violet-100">
              <p className="text-xs font-semibold text-violet-600 uppercase tracking-wider mb-1.5">Community Context</p>
              <p className="text-sm text-violet-800">{p.wealth_context_note}</p>
            </div>

            {/* Step 4: Fairness explanation card */}
            <div className="ml-10 p-4 bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl border border-emerald-100">
              <p className="text-xs font-semibold text-emerald-600 uppercase tracking-wider mb-1.5">Fairness Assessment</p>
              <p className="text-sm text-emerald-800">{p.fairness_explanation}</p>
            </div>
          </div>
        )}
      </div>

      {/* Risk & Positive Factors */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="card p-6">
          <h4 className="text-sm font-semibold text-red-600 uppercase tracking-wider mb-3">Risk Factors</h4>
          <div className="space-y-2">
            {(p.risk_factors || []).map((f, i) => (
              <div key={i} className="flex items-start gap-2">
                <svg className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
                </svg>
                <span className="text-sm text-stone-700">{f}</span>
              </div>
            ))}
            {(!p.risk_factors || p.risk_factors.length === 0) && (
              <p className="text-sm text-stone-400">No significant risk factors identified</p>
            )}
          </div>
        </div>

        <div className="card p-6">
          <h4 className="text-sm font-semibold text-emerald-600 uppercase tracking-wider mb-3">Positive Factors</h4>
          <div className="space-y-2">
            {(p.positive_factors || []).map((f, i) => (
              <div key={i} className="flex items-start gap-2">
                <svg className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                </svg>
                <span className="text-sm text-stone-700">{f}</span>
              </div>
            ))}
            {(!p.positive_factors || p.positive_factors.length === 0) && (
              <p className="text-sm text-stone-400">No additional positive factors</p>
            )}
          </div>
        </div>
      </div>

      {/* Repayment Reasoning */}
      <div className="card p-6">
        <h4 className="text-sm font-semibold text-stone-500 uppercase tracking-wider mb-2">Repayment Plan</h4>
        <p className="text-stone-700">{p.repayment_reasoning}</p>
      </div>

      {/* Comparison Chart */}
      <ComparisonChart fairloanRate={p.interest_rate_annual_percent} />

      {/* Traditional vs FairLoan — Side-by-side comparison */}
      <TraditionalComparison profile={p} wealthContext={wealthContext} applicantData={applicantData} loanAmount={loanAmount} />

      {/* FEATURE 2 — Government Scheme Matcher */}
      <div className="card p-6" id="scheme-matcher">
        <div className="flex items-center gap-2 mb-1">
          <svg className="w-5 h-5 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0 0 12 9.75c-2.551 0-5.056.2-7.5.582V21" />
          </svg>
          <h4 className="text-sm font-semibold text-stone-500 uppercase tracking-wider">Government Schemes</h4>
        </div>
        <p className="text-xs text-stone-400 mb-4">Find government schemes you may be eligible for based on your profile.</p>

        {!schemes && !schemesLoading && (
          <button
            onClick={fetchSchemes}
            className="btn-secondary text-sm"
            id="btn-check-schemes"
          >
            <svg className="w-4 h-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
            </svg>
            Check Eligible Schemes
          </button>
        )}

        {schemesLoading && (
          <div className="flex items-center gap-3 py-4">
            <svg className="animate-spin w-5 h-5 text-brand-600" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            <span className="text-sm text-stone-500">Finding matching government schemes...</span>
          </div>
        )}

        {schemesError && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm mt-2">
            {schemesError}
          </div>
        )}

        {schemes && schemes.length > 0 && (
          <div className="space-y-3 mt-2">
            {schemes.map((scheme, i) => (
              <div key={i} className="p-4 bg-gradient-to-r from-amber-50 to-yellow-50 rounded-xl border border-amber-200">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <h5 className="font-bold text-stone-900 text-sm">{scheme.name}</h5>
                    <p className="text-xs text-stone-600 mt-1">{scheme.description}</p>
                    <p className="text-xs text-amber-700 mt-1.5 font-medium">
                      <span className="font-semibold">Why eligible:</span> {scheme.eligibility_reason}
                    </p>
                  </div>
                  {scheme.application_url && (
                    <a
                      href={scheme.application_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex-shrink-0 px-3 py-1.5 bg-amber-600 text-white text-xs font-semibold rounded-lg hover:bg-amber-700 transition-colors"
                    >
                      Apply →
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Recommendations */}
      {p.recommendations && p.recommendations.length > 0 && (
        <div>
          <h4 className="text-sm font-semibold text-stone-500 uppercase tracking-wider mb-3">Recommendations</h4>
          <div className="space-y-3">
            {p.recommendations
              .sort((a, b) => {
                const order = { 'Urgent': 0, 'Suggested': 1, 'Optional': 2 };
                return (order[a.priority] ?? 2) - (order[b.priority] ?? 2);
              })
              .map((rec, i) => (
                <div key={i} className={`card p-4 border ${priorityColorMap[rec.priority] || 'border-stone-200'}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-xs font-bold uppercase ${
                      rec.priority === 'Urgent' ? 'text-red-600' :
                      rec.priority === 'Suggested' ? 'text-amber-600' : 'text-blue-600'
                    }`}>{rec.priority}</span>
                    <h5 className="font-semibold text-stone-900">{rec.title}</h5>
                  </div>
                  <p className="text-sm text-stone-600">{rec.description}</p>
                </div>
              ))}
          </div>
        </div>
      )}

      {/* Wealth Context Note — prominent callout */}
      <div className="card p-6 bg-gradient-to-r from-brand-50 to-emerald-50 border-brand-200" id="wealth-context-note">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center flex-shrink-0">
            <svg className="w-5 h-5 text-brand-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
            </svg>
          </div>
          <div>
            <h4 className="font-bold text-brand-800 mb-1">Why These Terms?</h4>
            <p className="text-brand-700">{p.wealth_context_note}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
